name: CMake & GoogleTest CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

      - name: Build XGBoost
        run: |
          cd xgboost
          mkdir -p build
          cd build
          cmake .. -G Ninja
          cmake --build .
        # This will produce libxgboost.so and/or libxgboost.a in xgboost/build

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DBUILD_FRONTEND=OFF -Dxgboost_DIR=${{ github.workspace }}/xgboost/build

      - name: Build
        run: cmake --build build

      - name: Run all backend test executables (show all test cases)
        run: |
          for exe in build/backend/Test*; do
            echo "Running $exe"
            $exe --gtest_color=yes
          done

      - name: Run tests (CTest summary)
        run: cd build/backend && ctest --output-on-failure
